Story8/urls.py
from django.urls import path
from . import views

app_name = 'Story8'

urlpatterns = [
    path('', views.ajax,name='ajax'),
    path('regis', views.regis,name='regis'),
]

Story9/urls.py
from django.urls import path
from . import views

app_name = 'Story9'

urlpatterns = [
    path('', views.main,name='main'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    #Path-Interface
    path('', views.index,name='index'),
    path('Blog/', views.blog,name='blog'),
    path('Projek/', views.Projek,name='projek'),
    path('Kegiatan/', views.kegiatan,name='kegiatan'),   
    path('About/',views.about,name='about'),   

    #View-Mata-Kuliah
    path('FormProduct',views.product_create_view, name= 'product_create'),
    path('ListProduct', views.list, name='product_list'),
    path('delete/<str:id>', views.delete, name="product_delete"),
    path('<int:id>',views.detail),
    path('update/<str:id>', views.update, name='update'),

    #View-Kegiatan
    path('Kegiatan', views.Kegiatan_create, name='card_kegiatan'),
    path('tambah', views.tambah, name='tambah'),
    path('tambah_peserta/', views.tambah_peserta, name='tambah_peserta'),

]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('Story8/', include('Story8.urls') , name = "Story8"),
    path('Story9/', include('Story9.urls') , name = "Story9"),
]

Story8/models.py
from django.db import models

# Create your models here.

Story9/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    namaMatkul = models.CharField(max_length = 30)
    dosen      = models.CharField(max_length = 30)
    jumlahSks  = models.IntegerField()
    semester   = models.IntegerField()
    ruangKelas = models.CharField(max_length = 6)

    def __str__(self):
        return self.namaMatkul

class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length = 200)

    def __str__(self):
        return self.namaKegiatan

class Peserta(models.Model):
    namaPeserta = models.CharField(max_length = 200)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kegiatan)+ "dan" + self.namaPeserta

Story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

home/forms.py
from django import forms

from .models import Product , Kegiatan , Peserta 

class ProductForm(forms.ModelForm):
    namaMatkul = forms.CharField(label=' Nama Matkul : ')
    dosen      = forms.CharField(label=' Nama Dosen   : ')
    jumlahSks  = forms.IntegerField(label=' Jumlah SKS : ')
    semester   = forms.CharField(label=' Semester  : ')
    ruangKelas = forms.CharField(label=' Ruang Kelas : ')
    
    class Meta:
        model = Product
        fields = '__all__'

class KegiatanForm(forms.ModelForm):
    namaKegiatan = forms.CharField(label='Nama Kegiatan : ')

    class Meta:
        model = Kegiatan
        fields = '__all__'
    
class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'

Story8/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def ajax(request):
    return render(request, 'home/ajax.html')

def regis(request):
    return render(request, 'home/depan.html')

Story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages


# Create your views here.

def main(request):
    return render(request, 'home/awal.html')

def logoutUser(request):
    logout(request)
    return redirect('Story9:main')

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('Story9:main')

    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('Story9:main')
            
            else:
                messages.info(request, 'Nama anda atau password anda salah...')
            
    context = {}
    return render(request, 'home/login.html', context)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('Story9:main')

    else:    
        form = CreateUserForm()
        if request.method =="POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Akun " + user + " sudah dibuat")
                return redirect('login')

    context = {'form':form}
    return render(request, 'home/register.html', context)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .forms import ProductForm , KegiatanForm , PesertaForm
from .models import Product , Kegiatan , Peserta

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def Projek(request):
    return render(request, 'home/Projek.html')

def blog(request):
    return render(request, 'home/blog.html')

def kegiatan(request):
    return render(request, 'home/kegiatan.html')

def about(request):
    return render(request, 'home/about.html')

def list(request):
    listp = Product.objects.all()
    return render(request, 'home/product_list.html' , {'listp':listp})

def product_create_view(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ListProduct')
    return render(request, 'home/product_create.html', {'form':form})

def delete(request,id):
    item = Product.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('/ListProduct')
    return render(request, 'home/product_delete.html', {'item':item})

def detail(request,id):
    prod = Product.objects.get(id=id)
    return render (request, 'home/product_detail.html',{'prod':prod})

def update(request, id):
    prod = Product.objects.get(id=id)
    form = ProductForm(instance=prod)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=prod)
        if form.is_valid():
            form.save()
            return redirect('/ListProduct')

    return render(request, 'home/product_create.html', {'form':form})

def Kegiatan_create(request):
    keg = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    keg_par = []

    for kegiatan in keg:
        kegiatan_partic = []

        for participant in peserta:
            if (str(participant.kegiatan) == str(kegiatan)):
                kegiatan_partic.append(participant)
        keg_par.append((kegiatan,kegiatan_partic))
        
    context= {
        'keg':keg,
        'keg_par' : keg_par,
        
    }
    return render(request, 'home/card_kegiatan.html', context)

def tambah(request):
    form = KegiatanForm()
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/Kegiatan')
    return render(request, 'home/kegiatan.html', {'form': form})


def tambah_peserta(request):
    form = PesertaForm()
    if request.method == 'POST':
       form = PesertaForm(request.POST)
       if form.is_valid():
           form.save()
           return redirect('/Kegiatan')
    return render(request, 'home/form_peserta.html',{'form':form})

Story8/templates/_navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Blog</title>




<link rel="stylesheet" href="../static/home/bootstrap-4.5.2-dist/css/bootstrap.css">

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="../static/home/js/script.js"></script>
<link rel="stylesheet" href="../static/home/Design.css">


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-#201F1F">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
		<a class="nav-link " href="{% url 'home:index' %}" style="color: white">Home </a>
		<a class="nav-link " href="{% url 'home:projek' %}" style="color: white">Project</a>
		<a class="nav-link " href="{% url 'home:blog' %}" style="color: white">Blog</a>
		<a class="nav-link " href="{% url 'home:product_list' %}" style="color: white">Jadwal</a>
    <a class="nav-link " href="{% url 'home:card_kegiatan' %}" style="color: white">Kegiatan</a>
    <a class="nav-link " href="{% url 'home:about' %}" style="color: white">About</a>
    <a class="nav-link " href="{% url 'Story8:ajax' %}" style="color: white">Story 8</a>
    <a class="nav-link " href="{% url 'Story9:main' %}" style="color: white">Story 9</a>
    </div>
  </div>
</nav>
</body>
</html>

Story8/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>

</head>
<body>
    {% include "_navbar.html"%}
    <div>
        {% block content %}
        {% endblock content %}  
    </div>

    <footer class="page-footer font-small blue" style="margin-top: 5%;">

        <div class="footer-copyright text-center py-3">© 2020 Copyright:
          <p style="color: #079211"> Kevin - 1906350811 </p>
        </div>
      
      </footer>
      
</body>
</html>

Story8/templates/home/ajax.html
{% extends "base.html" %}
    {% block content %}
    {% load static %}

<script src="{% static 'js\script.js' %}" type="text/javascript"></script>


<div style="margin-top: 48px;">
	
    <p class="heading" >Story 8</p>
    <p>Masukkan Nama Buku</p>
    <input id="keyword" placeholder="Masukkan Nama Buku"><br>
    <br><br>
    
    <table id="daftar_isi" class="table table-bordered">   

    </table>
    

<script>
    $("#keyword").keyup(function() {
        var ketikan = $("#keyword").val();
        console.log(ketikan);

        $.ajax({
            url : 'https://www.googleapis.com/books/v1/volumes?q=' + ketikan,
            success : function(data)  {
                var array_items = data.items;
                console.log(data);

                 $("#daftar_isi").empty();
                 $("#daftar_isi").append( "<tr><td> No </td><td>Judul</td><td>Penulis</td><td>Gambar Buku</td></tr>");

                 for ( i = 0 ; i <array_items.length;i++){
                     var judul = array_items[i].volumeInfo.title;
                     var penulis = array_items[i].volumeInfo.authors[0];
                     var gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
                     

                     $("#daftar_isi").append( "<tr><td> "+ i + "</td><td>"  + judul  +  "</td><td>" + penulis +"</td><td><img src= " + gambar + "></td></tr>");


                    
                 }
            }     
        });

    });


</script>

</body>
</html>

{% endblock %}

Story9/templates/_navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Blog</title>




<link rel="stylesheet" href="../static/home/bootstrap-4.5.2-dist/css/bootstrap.css">

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="../static/home/js/script.js"></script>

<link rel="stylesheet" href="../static/Design.css">


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-#201F1F">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
		<a class="nav-link " href="{% url 'home:index' %}" style="color: white">Home </a>
		<a class="nav-link " href="{% url 'home:projek' %}" style="color: white">Project</a>
		<a class="nav-link " href="{% url 'home:blog' %}" style="color: white">Blog</a>
		<a class="nav-link " href="{% url 'home:product_list' %}" style="color: white">Jadwal</a>
    <a class="nav-link " href="{% url 'home:card_kegiatan' %}" style="color: white">Kegiatan</a>
    <a class="nav-link " href="{% url 'home:about' %}" style="color: white">About</a>
    <a class="nav-link " href="{% url 'Story8:ajax' %}" style="color: white">Story 8</a>
    <a class="nav-link " href="{% url 'Story9:main' %}" style="color: white">Story 9</a>
    </div>
  </div>
</nav>
</body>
</html>

Story9/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>

</head>
<body>
    {% include "_navbar.html"%}
    <div>
        {% block content %}
        {% endblock content %}  
    </div>

    <footer class="page-footer font-small blue" style="margin-top: 5%;">

        <div class="footer-copyright text-center py-3">© 2020 Copyright:
          <p style="color: #079211"> Kevin - 1906350811 </p>
        </div>
      
      </footer>
      
</body>
</html>

Story9/templates/home/awal.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<p class="heading" >Story 9</p>

    <div class="container">

        {% if user.is_authenticated %}

        <p> Selamat datang {{ request.user.username }}! </p>
        <p> Tekan logout jika mau logout </p>
        <div class="text-center">
          <a class="btn btn-primary btn-lg" href="{% url 'Story9:logout' %}" button>Logout</a>
        </div>

        {% else %}

        <p> Selamat datang ! </p>
        <p> Login atau daftar terlebih dahulu </p>
        <div class="text-center">
          <a class="btn btn-primary btn-lg" href="{% url 'Story9:login' %}" button>Login</a><br><br>
          <a class="btn btn-primary btn-lg" href="{% url 'Story9:register' %}" button>Daftar</a>
        </div>

        {% endif %}

    </div>


{% endblock %}

Story9/templates/home/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<center>
			<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


			<h3 id="form-title">MASUK</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Nama..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="login">
				   			</div>
					</form>

				</div>
                
                {% for message in messages %}
                    <p id=messages> {{message}} </p>
				{% endfor %}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Belum memiliki akun? <a href="{% url 'Story9:register' %}" class="ml-2">Daftar</a>
					</div>
			
				</div>
			</div>
		</div>	

	</center>

{% endblock %}

Story9/templates/home/register.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<center>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">PENDAFTARAN AKUN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Daftarkan Akun">
				   		</div>
					</form>
                </div>
                
                {{form.errors}}
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Sudah memiliki akun? <a href="{% url 'Story9:login' %}" class="ml-2">Masuk</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</center>

	<script>
	var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nama..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Ketik Password...';
		form_fields[4].placeholder='Ketik Ulang Password...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
{% endblock %}

home/templates/_navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title></title>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



<link rel="stylesheet" href="../static/home/bootstrap-4.5.2-dist/css/bootstrap.css">
<link rel="stylesheet" href="../static/home/Design.css">


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-#201F1F">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
		<a class="nav-link " href="{% url 'home:index' %}" style="color: white">Home </a>
		<a class="nav-link " href="{% url 'home:projek' %}" style="color: white">Project</a>
		<a class="nav-link " href="{% url 'home:blog' %}" style="color: white">Blog</a>
		<a class="nav-link " href="{% url 'home:product_list' %}" style="color: white">Jadwal</a>
    <a class="nav-link " href="{% url 'home:card_kegiatan' %}" style="color: white">Kegiatan</a>
    <a class="nav-link " href="{% url 'home:about' %}" style="color: white">About</a>
    <a class="nav-link " href="{% url 'Story8:ajax' %}" style="color: white">Story 8</a>
    <a class="nav-link " href="{% url 'Story9:main' %}" style="color: white">Story 9</a>
    </div>
  </div>
</nav>
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>

</head>
<body>
    {% include "_navbar.html"%}
    <div>
        {% block content %}
        {% endblock content %}  
    </div>

    <footer class="page-footer font-small blue" style="margin-top: 5%;">

        <div class="footer-copyright text-center py-3">© 2020 Copyright:
          <p style="color: #079211"> Kevin - 1906350811 </p>
        </div>
      
      </footer>
      
</body>
</html>

home/templates/home/Kegiatan.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container">
      <br>
      <p class="heading">Tambah Kegiatan</p>
      <p>Story-6</p>
      <hr class="mt-0 mb-4">
      <form method="POST">
        {% csrf_token %} 
        {{ form|crispy }}
        <br>
        <br>
        <button type="submit" class="btn btn-primary" style="background-color: #079211; border:none ;">Submit</button>
        <a type="button" class="btn btn-light" href="{% url 'home:card_kegiatan' %}"><b style="color: black ; background-color: white;">Back</b></a>
      </form>

</div>

</body>
</html>

{% endblock %}

home/templates/home/Projek.html
{% extends "base.html" %}
    {% block content %}
    {% load static %}

<div style="margin-top: 48px;">
	
	<p class="heading" >Projek Saya</p>
	<a href="https://www.behance.net/gallery/90833931/UX-Case-Study-Teman-Pacil" target="_blank"><img src="../../static/home/gambar/Cover.jpg" alt="TemanPacil" width="100%" style="margin-top:24px;"></a>
	<img src="../../static/home/gambar/Coming.png" alt="TemanPacil" width="100%" style="margin-top:48px;"></a>



</body>
</html>

{% endblock %}

home/templates/home/card_kegiatan.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="container">
        <div class="container-fluid justify-content-center">
            <div class="row justify-content-center"></div>
            <h2 class="featurette-heading">
            <br>
            <p class="heading">List Kegiatan</p>
            <p>Story-6</p>
            <br> 
            <a class="btn btn-dark justify-content-center " href="{% url 'home:tambah' %}" style="background-color: #079211;">Tambah Aktifitas</a>
            <br>
            <br> 

           {% for a in keg_par %}
          
            <div class="row justify-content-center">
                <div class="col-sm-4">
                    <div class="card border-primary mb-4" style="max-width: 24rem;">
                    <div class="card-header" style="background-color: #079211;">{{ a.0.namaKegiatan }}</div>
                    <div class="card-body text-primary" style="border: white;">
                        <p class="card-text">  
                            <p>Nama Peserta</p>
                            <p>{% for b in a.1 %}</p>
                            <p> - {{ b.namaPeserta }} </p>
                            {% endfor %}
                            <a type="button" class="btn btn-info" style="background-color: #079211" href="{% url 'home:tambah_peserta' %}">Ikut Aktifitas</a>
                        </p>

                    </div>
                    </div>
                </div>
            </div>
        </div>
            {% endfor %}

</div>      
</body>
</html>

{% endblock %}

home/templates/home/form_peserta.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container">
        <br>
        <p class="heading">Daftar Aktifitas</p>
        <p>Story-6</p>

        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %} 
          {{ form|crispy }}
          <br>
          <br>
          <button type="submit" class="btn btn-primary" style="background-color: #079211; border:none ;">Submit</button>
          <a type="button" class="btn btn-light" style="background-color: #FFF; border:none" href="{% url 'home:card_kegiatan' %}">Back</a>
        </form>
</div>

</body>
</html>

{% endblock %}

home/templates/home/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<p class="heading">Susun Jadwal</p>
<p>Story-5</p>


<div class="container-fluid padding">
        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
          <br>
          <br>
          <button type="submit" class="btn btn-primary" style="background-color: #079211; border:none ;">Submit</button>
          <a type="button" class="btn btn-light" style="background-color: #FFF; border:none" href="{% url 'home:product_list' %}"><b style="background-color: #FFF; color: black;">Back</b></a>
        </form>
</div>

<br>


{% endblock %}

home/templates/home/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<p class="heading">Susun Jadwal</p>
<p>Story-5</p>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
        
        <form action="{% url 'home:product_delete' item.id %}" method='POST'>
            {% csrf_token %}
            <h5 class="featurette-heading">Do you want to delete the course "{{item}}"?</h5>
            <br>
            <button type="submit" class="btn btn-info" style="background-color: #079211 ; border: none;"><b style="background-color: #079211">Yes</b></button>
            <a type="button"  class="btn btn-danger" style="background-color: red;" href = "{% url 'home:product_list' %}" ><b style="background-color: red;">Cancel</b></a>

      </div>
    </div>
  </div>

{% endblock %}

home/templates/home/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<p class="heading">Susun Jadwal</p>
<p>Story-5</p>

<br>
<div class="container-fluid padding">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Course Detail</b></h2>
        <table class="table" style="text-align: left; background-color: white;" >
        <tbody >
          <tr>
            <th scope="row">Nama matkul</th>
            <td>{{ prod.namaMatkul }}</td>
          </tr>
          <tr>
            <th scope="row">Dosen</th>
            <td>{{ prod.dosen }}</td> 
          </tr>
          <tr>
            <th scope="row">Sks</th>
            <td>{{ prod.jumlahSks }}</td>
          </tr>
          <tr>
            <th scope="row">Semester</th>
            <td>{{ prod.semester }}</td>
          </tr>
          <tr>
            <th scope="row">Ruang Kelas</th>
            <td>{{ prod.ruangKelas }}</td>
          </tr>
        </tbody>
      </table>
      
      <a type="button" class="btn btn-light" href="{% url 'home:product_list' %}"><b style="background-color: #FFF; border:none ; color: black;">Back</b></a>
      <center>
      <a type="button" class="btn btn-info" href="{% url 'home:update' prod.id %}" style="background-color: #079211; border:none">Update Course</a>
      <a class="btn btn-danger" href="{% url 'home:product_delete' prod.id %}">Delete Course</a>
      </center>
      
  </div>
</div>
</div>

{% endblock %}

home/templates/home/product_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<p class="heading">Susun Jadwal</p>
<p>Story-5</p>

<br>
  <div class="container-fluid padding">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Mata Kuliah yang diambil</b></h2>
        <hr class="mt-0 mb-4">
        <div class="list-group">
            {% for i in listp %}
            <a href="{{ i.id }}" class="list-group-item list-group-item-action"><b style="background-color:#FFF; color: black;">{{ i.namaMatkul }}</b></a>
            {% endfor %}
        </div>
        <br>
        <a class="btn btn-dark" style="background-color:#079211;" href="{% url 'home:product_create' %}"><b style="background-color:#079211; color:#FFF;">Tambah Matakuliah</b></a>
      <br>
    </div>
  </div>
</div>

{% endblock %}